version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:3000"  # Backend server
      - "5173:5173"  # Vite dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key-here}
      - PORT=3000
      - VITE_HOST=0.0.0.0
    command: npm run dev:all